services:
  api:
    build: ./api
    ports:
      - "42424:42424"
    depends_on:
      - db
    env_file:
      - ./react-showcase/.env
    develop:
      watch:
        - action: sync+restart
          path: ./api
          target: /api
          ignore:
            - ./api/requirements.txt
        - action: rebuild
          path: ./api/requirements.txt
    working_dir: /api
    command: uvicorn main:app --host 0.0.0.0 --port 42424

  db:
    image: postgres:15
    container_name: db_app
    environment:
      POSTGRES_DB: ${DB_NAME:-postgres}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    ports:
      - "5432:5432"
    expose:
      - 1221
    command: ["postgres", "-p", "1221"]
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./react-showcase/.env
    restart: always

  app:
    # restart: always
    build: ./react-showcase
    ports:
      - "127.0.0.1:80:3000"
    depends_on:
      - api
volumes:
  postgres_data: