FROM node:22

WORKDIR /app

COPY package.json package-lock.json .

RUN --mount=type=cache,target=/root/.npm npm install


COPY next.config.ts postcss.config.mjs tsconfig.json .

COPY public/ public/

COPY src/ src/

EXPOSE 3000

RUN ["npm", "run", "build"]

CMD ["npm", "run", "start"]
