FROM node:22

# Создаём рабочую директорию
WORKDIR /app

# Копируем только package-файлы и устанавливаем зависимости (с кэшем)
COPY package.json package-lock.json ./
RUN --mount=type=cache,target=/root/.npm npm install

# Копируем весь остальной проект (включая src/, public/, next.config.js и пр.)
COPY . .

# Открываем порт
EXPOSE 3000

# Сборка проекта
RUN npm run build

# Запуск в production-режиме
CMD ["npm", "run", "start", "--", "-H", "0.0.0.0", "--port", "3000"]
