FROM python:3.13

RUN --mount=type=bind,source=requirements.txt,target=/tmp/requirements.txt \
    --mount=type=cache,target=/root/.cache/pip \
    pip install -r /tmp/requirements.txt

WORKDIR /api

COPY *.py .

EXPOSE 42424

CMD ["fastapi", "run", "main.py", "--port", "42424"]
