FROM tiangolo/uvicorn-gunicorn-fastapi:python3.11

RUN --mount=type=bind,source=requirements.txt,target=/tmp/requirements.txt \
    --mount=type=cache,target=/root/.cache/pip \
    pip install -r /tmp/requirements.txt

WORKDIR /api

COPY *.py .

EXPOSE 42424

CMD ["uvicorn", "main:app", "--port", "42424"]